export interface Project {
  id: string
  title: string
  description: string
  longDescription: string
  liveUrl: string
  repoUrl: string
  imageUrl: string
  technologies: string[]
  features: string[]
  stats: {
    label: string
    val: string
    color: string
  }[]
  codeSnippet: {
    file: string
    language: string
    lines: string[]
  }
}

export const projects: Project[] = [
  {
    id: 'saviorperu',
    title: 'SaviorPeru - Ecommerce de Moda con Admin Panel',
    description:
      'Plataforma e-commerce para ropa y accesorios con panel de administración completo y gestión de colecciones destacadas.',
    longDescription:
      'Tienda online desarrollada en Next.js que combina un catálogo de productos públicos con un panel de administración para gestionar colecciones, productos destacados y configuraciones de la tienda. Implementa validaciones con Zod, gestión de imágenes con Cloudinary, paginación y búsqueda en tiempo real, y mantiene un límite de 4 colecciones activas.',
    liveUrl: 'https://saviorperu.vercel.app',
    repoUrl: 'https://github.com/SaviorPeru/SaviorPeru',
    imageUrl:
      'https://res.cloudinary.com/dniekrmqb/image/upload/q_auto,w_800/v1746419358/portafolio/saviorperu.com_orql0e.webp',
    technologies: [
      'Next.js 14',
      'React 18',
      'TypeScript',
      'Tailwind CSS',
      'Zod',
      'Cloudinary',
      'PostgreSQL',
      'Prisma ORM',
      'Clerk (Autenticación)',
      'Vercel',
      'React Hook Form',
      'Toast Notifications'
    ],
    features: [
      'Catálogo de productos con imágenes múltiples',
      'Sistema de colecciones destacadas (máximo 4)',
      'Panel de administración con CRUD completo',
      'Gestión de imágenes integrada con Cloudinary',
      'Búsqueda y paginación en tiempo real',
      'Validaciones de formulario con Zod',
      'Estados de carga con skeletons',
      'Manejo de errores con reintentos',
      'Configuración de tienda (delivery, contacto, redes)',
      'Interfaz responsive y modo oscuro',
      'Productos destacados en homepage',
      'Sistema de stock y estados de producto'
    ],
    stats: [
      { label: 'Performance', val: '94%', color: 'text-green-400' },
      { label: 'SEO', val: '92%', color: 'text-blue-400' },
      { label: 'Accessibility', val: '89%', color: 'text-yellow-400' },
      { label: 'Commits', val: '102+', color: 'text-purple-400' }
    ],
    codeSnippet: {
      file: 'app/admin-panel/components/SettingsManagement.tsx (Admin Panel - Gestión de Colecciones)',
      language: 'TypeScript',
      lines: [
        'const coleccionSchema = z.object({',
        ' name: z',
        '  .string()',
        '  .min(1, "El nombre es requerido")',
        '  .max(100, "Nombre muy largo"),',
        ' image: z.string().url("La imagen debe ser una URL válida")',
        '})',
        '',
        'const handleSaveColeccion = async () => {',
        ' try {',
        '  const validatedData = coleccionSchema.parse(coleccionForm)',
        '  setColeccionErrors({ name: "", image: "" })',
        '',
        '  if (colecciones.length >= 4 && !selectedColeccion) {',
        '   toast.error("Máximo 4 colecciones permitidas")',
        '   return',
        '  }',
        '',
        '  const response = await fetch("/api/colecciones", {',
        '   method: selectedColeccion ? "PUT" : "POST",',
        '   headers: { "Content-Type": "application/json" },',
        '   body: JSON.stringify(validatedData)',
        '  })',
        '',
        '  if (!response.ok) throw new Error()',
        "  toast.success(Colección ${selectedColeccion ? 'actualizada' : 'creada'})",
        '  resetColeccionForm()',
        '  fetchColecciones(searchTerm)',
        ' } catch (error) {',
        '  if (error instanceof z.ZodError) {',
        '   const errors = { name: "", image: "" }',
        '   error.errors.forEach((err) => {',
        '    if (err.path[0]) {',
        '     const key = err.path[0].toString() as "name" | "image"',
        '     errors[key] = err.message',
        '    }',
        '   })',
        '   setColeccionErrors(errors)',
        '  }',
        ' }',
        '}'
      ]
    }
  },
  {
    id: 'pascomovil',
    title:
      'Pascomovil - Sistema Full-Stack de Reservas de Transporte Interprovincial',
    description:
      'Plataforma full-stack de reservas de viajes en bus entre Lima y Cerro de Pasco con selección visual de asientos, confirmación por WhatsApp y panel administrativo.',
    longDescription:
      'Sistema completo de reservas de transporte interprovincial que integra una aplicación web para usuarios finales, una API REST robusta y un panel administrativo. Permite búsqueda de viajes, selección visual de asientos, autenticación segura, generación automática de horarios basada en flota, protección de viajes con reservas activas y gestión administrativa con control de estados.',
    liveUrl: 'https://pascomovil.vercel.app',
    repoUrl: 'https://github.com/cterryc/pascomovil',
    imageUrl:
      'https://res.cloudinary.com/dniekrmqb/image/upload/q_auto,w_800/v1770085492/portafolio/Opera_Snapshot_2026-02-02_212426_pascomovil.vercel.app_hb6l5i.webp',
    technologies: [
      'React 18',
      'Vite',
      'Redux Toolkit',
      'Redux Persist',
      'React Router',
      'Tailwind CSS',
      'Axios',
      'SweetAlert2',
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'Sequelize ORM',
      'JWT (httpOnly cookies)',
      'bcrypt',
      'Brevo (Email Service)',
      'React 19',
      'SWC Compiler',
      'Vercel',
      'Railway'
    ],
    features: [
      'Búsqueda de viajes por origen, destino y fecha',
      'Calendario dinámico con reglas de disponibilidad',
      'Selección visual de asientos con estados en tiempo real',
      'Flujo de reserva progresivo con validación por pasos',
      'Confirmación de reservas vía WhatsApp con mensaje dinámico',
      'Autenticación completa con recuperación de contraseña',
      'Historial de reservas por usuario',
      'Generación automática de viajes IDA y VUELTA por flota',
      'Protección de viajes con reservas activas (inmutables)',
      'Gestión de 7 asientos por viaje con cálculo automático',
      'Autenticación JWT con cookies httpOnly',
      'Middleware de autorización por roles (admin)',
      'Tareas automatizadas para cierre de reservas pasadas',
      'Panel administrativo con CRUD completo',
      'Gestión de usuarios, viajes, vehículos y destinos',
      'Control de estados de reservas con confirmaciones visuales',
      'Dashboard con estadísticas generales'
    ],
    stats: [
      { label: 'Performance', val: '92%', color: 'text-green-400' },
      { label: 'Seo', val: '92%', color: 'text-blue-400' },
      { label: 'Accessibility', val: '90%', color: 'text-yellow-400' },
      { label: 'Commits', val: '30+', color: 'text-purple-400' }
    ],
    codeSnippet: {
      file: 'src/services/trip.service.js (Backend – Generación Automática de Horarios)',
      language: 'JavaScript',
      lines: [
        '// Implementación clave: Generación automática e inteligente de viajes',
        '// Origen: objeto pacomovil-api (Backend)',
        '',
        '// Lógica de regeneración basada en flota y protección de reservas activas',
        'if (trips.length < expectedTotalTrips) {',
        '  console.log(`[REGENERACIÓN] Flota incompleta (${trips.length}/${expectedTotalTrips})`)',
        '',
        '  // Agrupar viajes existentes por carId',
        '  const tripsByCarId = new Map()',
        '  trips.forEach((trip) => {',
        '    if (trip.carId) {',
        '      if (!tripsByCarId.has(trip.carId)) {',
        '        tripsByCarId.set(trip.carId, [])',
        '      }',
        '      tripsByCarId.get(trip.carId).push(trip)',
        '    }',
        '  })',
        '',
        '  // Iterar sobre la flota actual',
        '  for (const car of fleetSchedule) {',
        '    const existingTrips = tripsByCarId.get(car.id) || []',
        '',
        '    // Proteger viajes con reservas activas (INMUTABLES)',
        '    const hasActiveReservation = existingTrips.some(',
        '      (t) => t.Reservations && t.Reservations.length > 0',
        '    )',
        '',
        '    if (hasActiveReservation) {',
        '      console.log(`Carro ${car.id} tiene reservas activas, se mantiene inmutable.`)',
        '      continue',
        '    }',
        '',
        '    // Eliminar viajes previos sin reservas',
        '    if (existingTrips.length > 0) {',
        '      const tripIdsToDelete = existingTrips.map((t) => t.id)',
        '',
        '      await Seat.destroy({',
        '        where: { tripId: { [Op.in]: tripIdsToDelete } }',
        '      })',
        '',
        '      await Trip.destroy({',
        '        where: { id: { [Op.in]: tripIdsToDelete } }',
        '      })',
        '    }',
        '',
        '    // Definir ciclo IDA / VUELTA según ciudad de origen',
        '    const origin = car.departureCityName.toLowerCase()',
        '    let idaFromId, idaToId, vueltaFromId, vueltaToId',
        '',
        '    if (origin === "lima") {',
        '      idaFromId = LIMA_ID',
        '      idaToId = PASCO_ID',
        '      vueltaFromId = PASCO_ID',
        '      vueltaToId = LIMA_ID',
        '    } else if (origin === "cerro de pasco") {',
        '      idaFromId = PASCO_ID',
        '      idaToId = LIMA_ID',
        '      vueltaFromId = LIMA_ID',
        '      vueltaToId = PASCO_ID',
        '    }',
        '',
        '    // Crear viajes IDA y VUELTA con 7 asientos cada uno',
        '    await this.createTrip({',
        '      date,',
        '      time: car.fixedDepartureTime,',
        '      fromId: idaFromId,',
        '      toId: idaToId,',
        '      carId: car.id',
        '    })',
        '',
        '    await this.createTrip({',
        '      date,',
        '      time: car.returnDepartureTime,',
        '      fromId: vueltaFromId,',
        '      toId: vueltaToId,',
        '      carId: car.id',
        '    })',
        '  }',
        '}'
      ]
    }
  },
  {
    id: 'grimreaper',
    title: 'GrimReaper - Sistema Full-Stack de Gestión DKP para WoW',
    description:
      'Aplicación full-stack para gestión de DKP (Dragon Kill Points) en World of Warcraft 3.3.5a',
    longDescription:
      'Sistema completo de gestión de clan para World of Warcraft que combina una SPA en React con una API RESTful en Express. Procesa exportaciones XML de DKP, gestiona personajes Main/Alter con PostgreSQL, implementa versionado temporal por zona horaria Perú (UTC-5) y utiliza un microservicio externo para scraping optimizado de equipamiento desde Warmane.',
    liveUrl: 'https://grimreaper.vercel.app',
    repoUrl: 'https://github.com/cterryc/Grimreaper',
    imageUrl:
      'https://res.cloudinary.com/dniekrmqb/image/upload/q_auto,w_800/v1725046794/portafolio/jthrlgwhpmzywde9oq7q.webp',
    technologies: [
      'React 18.3.1',
      'Vite 5.3.1',
      'Redux Toolkit',
      'Redux Persist',
      'Material-UI',
      'Express.js 4.19.2',
      'PostgreSQL',
      'Sequelize 6.6.5',
      'xml2js 0.6.2',
      'bcrypt 5.1.1',
      'Puppeteer',
      'Vercel',
      'Railway (Microservicio)'
    ],
    features: [
      'Sistema DKP con ordenamiento múltiple (clase, nombre, rango, puntos)',
      'Procesamiento XML de DKP con categorización automática Main/Alter',
      'Navegación temporal de snapshots DKP (actual, -1 día, -2 días)',
      'Sistema de backup cascada de dos niveles con snapshots temporales',
      'Resolución de referencias encadenadas de personajes Alter',
      'Scraping dinámico de equipamiento desde armory.warmane.com',
      'Visualización interactiva de ítems con tooltips y gemas',
      'Catálogo Best-in-Slot por clase y especialización',
      'Autenticación de administradores',
      'Persistencia de estado en frontend con redux-persist',
      'Configuración dual: desarrollo local y producción',
      'Integración con microservicio externo de scraping optimizado'
    ],
    stats: [
      { label: 'Performance', val: '100%', color: 'text-green-400' },
      { label: 'SEO', val: '88%', color: 'text-blue-400' },
      { label: 'Accessibility', val: '95%', color: 'text-yellow-400' },
      { label: 'Commits', val: '125+', color: 'text-blue-400' }
    ],
    codeSnippet: {
      file: 'scraper-service/index.js (Backend – Microservicio de Scraping)',
      language: 'JavaScript',
      lines: [
        '// Sistema de caché en memoria para reducir scraping repetido',
        'const cache = new Map()',
        'const CACHE_DURATION = 5 * 60 * 1000 // 5 minutos',
        '',
        'app.get("/api/:character", async (req, res) => {',
        '  const { character } = req.params',
        '  const cacheKey = character.toLowerCase()',
        '  const cachedData = cache.get(cacheKey)',
        '',
        '  // Retornar desde caché si está disponible',
        '  if (cachedData && Date.now() - cachedData.timestamp < CACHE_DURATION) {',
        '    return res.status(200).send(cachedData.data)',
        '  }',
        '',
        '  // Configuración optimizada para Railway (memoria limitada)',
        '  const options = {',
        '    headless: "new",',
        '    args: [',
        '      "--no-sandbox",',
        '      "--disable-setuid-sandbox",',
        '      "--disable-dev-shm-usage",',
        '      "--memory-pressure-off",',
        '      "--max_old_space_size=256"',
        '    ]',
        '  }',
        '',
        '  const browser = await puppeteer.launch(options)',
        '  const page = await browser.newPage()',
        '',
        '  // Bloquear recursos pesados para ahorrar memoria',
        '  await page.setRequestInterception(true)',
        '  page.on("request", (request) => {',
        '    if (["image", "stylesheet", "font", "media"].includes(request.resourceType())) {',
        '      request.abort()',
        '    } else {',
        '      request.continue()',
        '    }',
        '  })',
        '',
        '  // Detección de Cloudflare Challenge',
        '  const titleText = await page.evaluate(el => el.textContent, await page.$("title"))',
        '  if (titleText.includes("Verificar que usted es un ser humano")) {',
        '    throw new Error("Cloudflare challenge detected")',
        '  }',
        '',
        '  const elementos = await page.evaluate(() => {',
        '    return {',
        '      left: extractElementsAttributes(document.querySelectorAll(".item-left div div a")),',
        '      right: extractElementsAttributes(document.querySelectorAll(".item-right div div a")),',
        '      bottom: extractElementsAttributes(document.querySelectorAll(".item-bottom div div a")),',
        '      scrapedAt: new Date().toISOString()',
        '    }',
        '  })',
        '',
        '  // Guardar en caché (máximo 50 personajes)',
        '  cache.set(cacheKey, { data: elementos, timestamp: Date.now() })',
        '  if (cache.size > 50) cache.delete(cache.keys().next().value)',
        '',
        '  await browser.close()',
        '  res.status(200).send(elementos)',
        '})'
      ]
    }
  },
  {
    id: 'marteldev',
    title: 'MartelDev - Landing Page de Templates E-commerce',
    description:
      'Landing page para venta de templates e-commerce con sistema de paquetes y galería de diseños.',
    longDescription:
      'Aplicación SPA desarrollada en React que presenta 5 templates de e-commerce pre-diseñados con 3 paquetes de servicio (Frontend, Fullstack, Personalizado). Implementa arquitectura JAMstack con datos estáticos centralizados en DTOs, integración con WhatsApp para conversión directa, y optimización de imágenes con Cloudinary. Sistema de routing client-side con React Router y despliegue en Vercel Edge Network.',
    liveUrl: 'https://marteldev.vercel.app',
    repoUrl: 'https://github.com/cterryc/marteldev-landingpage',
    imageUrl:
      'https://res.cloudinary.com/dniekrmqb/image/upload/q_auto,w_800/v1769099780/MartelDev-Ecommerce/1_fkjd7g.webp',
    technologies: [
      'React 19',
      'TypeScript',
      'Vite',
      'React Router v7',
      'Tailwind CSS',
      'Cloudinary',
      'Vercel',
      'WhatsApp Web API'
    ],
    features: [
      'Galería de 5 templates e-commerce especializados',
      'Sistema de 3 paquetes de servicio (S/ 499 - S/ 1499)',
      'Arquitectura JAMstack sin backend',
      'Datos centralizados en DTOs TypeScript',
      'Integración directa con WhatsApp para conversión',
      'Optimización automática de imágenes (Cloudinary)',
      'Routing client-side con SPA',
      'Tabla comparativa de paquetes',
      'Páginas de detalle por template',
      'Textos alt comprehensivos para accesibilidad',
      'Despliegue en Edge Network global',
      'Rewrite rules para SPA routing'
    ],
    stats: [
      { label: 'Performance', val: '99%', color: 'text-green-400' },
      { label: 'Seo', val: '92', color: 'text-blue-400' },
      { label: 'Accessibility', val: '95', color: 'text-yellow-400' },
      { label: 'Commits', val: '6+', color: 'text-purple-400' }
    ],
    codeSnippet: {
      file: 'components/PackageCard.tsx (Sistema de Paquetes - Lógica de CTA)',
      language: 'TypeScript',
      lines: [
        'const PackageCard: React.FC<{ pkg: Package }> = ({ pkg }) => {',
        '  const navigate = useNavigate()',
        '  return (',
        '    <div className={`bg-charcoal border ${pkg.isPopular ? "border-2 border-primary" : "border-cream/10"}`}>',
        '      {pkg.isPopular && (',
        '        <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary text-dark">',
        '          Más Popular',
        '        </div>',
        '      )}',
        '      ',
        '      {/* Feature list rendering */}',
        '      {pkg.features.map((feature, idx) => (',
        '        <div key={idx} className="flex items-start gap-3">',
        '          <svg className="w-5 h-5 text-primary">',
        '            <path d="M5 13l4 4L19 7" />',
        '          </svg>',
        '          <span>{feature}</span>',
        '        </div>',
        '      ))}',
        '',
        '      {/* Conditional CTA logic */}',
        '      <button',
        '        onClick={() => {',
        '          if (pkg.ctaText === "Cotizar por WhatsApp") {',
        '            contactWhatsApp(pkg.ctaText)',
        '          } else {',
        '            navigate("/templates")',
        '          }',
        '        }}',
        '      >',
        '        {pkg.ctaText}',
        '      </button>',
        '    </div>',
        '  )',
        '}'
      ]
    }
  },
  {
    id: 'videogames',
    title: 'Videogames App - Catálogo Interactivo',
    description: 'Aplicación de catálogo de videojuegos con búsqueda avanzada',
    longDescription:
      'Proyecto académico full-stack desarrollado en Henry Bootcamp que consume la API RAWG para mostrar videojuegos con sistema de búsqueda, filtrado y creación de videojuegos personalizados.',
    liveUrl: 'https://videogames-terry.vercel.app',
    repoUrl: 'https://github.com/cterryc/PI-Videogames-Vite',
    imageUrl:
      'https://res.cloudinary.com/dniekrmqb/image/upload/q_auto,w_800/v1712559020/portafolio/zsve4caj9xzql0lotdna.webp', // Añadir URL después
    technologies: [
      'React.js',
      'Redux',
      'Express.js',
      'PostgreSQL',
      'Sequelize',
      'Axios',
      'RAWG API'
    ],
    features: [
      'Búsqueda y filtrado avanzado de videojuegos',
      'Consumo de API RAWG para datos actualizados',
      'Formulario controlado para crear videojuegos',
      'Ordenamiento múltiple (alfabético, rating, fecha)',
      'Base de datos PostgreSQL con Sequelize ORM',
      'Frontend responsive con React y Redux'
    ],
    stats: [
      { label: 'Performance', val: '94%', color: 'text-green-400' },
      { label: 'SEO', val: '85%', color: 'text-blue-400' },
      { label: 'Accessibility', val: '89%', color: 'text-yellow-400' },
      { label: 'Commits', val: '64', color: 'text-purple-400' }
    ],
    codeSnippet: {
      file: 'actions/gamesActions.js',
      language: 'JavaScript',
      lines: [
        '// Consumo de API RAWG para obtener videojuegos',
        'export const fetchGames = (filters = {}) => async (dispatch) => {',
        "  dispatch({ type: 'LOADING_GAMES' });",
        '  ',
        '  try {',
        '    const params = new URLSearchParams({',
        '      key: process.env.RAWG_API_KEY,',
        '      page_size: 40,',
        '      ...filters',
        '    });',
        '    ',
        '    const response = await axios.get(',
        '      `https://api.rawg.io/api/games?${params}`',
        '    );',
        '    ',
        '    const games = response.data.results.map((game) => ({',
        '      id: game.id,',
        '      name: game.name,',
        '      released: game.released,',
        '      rating: game.rating,',
        '      background_image: game.background_image,',
        '      genres: game.genres.map((g) => g.name),',
        '      platforms: game.platforms.map((p) => p.platform.name)',
        '    }));',
        '    ',
        '    dispatch({',
        "      type: 'SET_GAMES',",
        '      payload: { games, total: response.data.count }',
        '    });',
        '  } catch (error) {',
        '    dispatch({',
        "      type: 'SET_ERROR',",
        "      payload: 'Error al cargar videojuegos'",
        '    });',
        '  }',
        '};'
      ]
    }
  }
]

// Proyecto por defecto
export const defaultProject = projects[0]
